import { colors } from "./Theme"
module.exports = {
    sformcontainer: {
        flex: 1,
        backgroundColor: 'white',
        // alignItems: 'center',
        justifyContent: 'center',
        width: '90%',
        // padding: 10,
        alignSelf: 'center',
        marginTop: 10,
        borderRadius: 20,
        overflow: 'hidden',
      },
      sformcontainerin: {
        // backgroundColor: 'yellow',
        paddingVertical: 5,
        paddingHorizontal: 20,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
      },
      sformcontainerin2: {
        paddingVertical: 5,
        paddingHorizontal: 20,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
      },
      sformhead: {
        fontSize: 20,
        backgroundColor: colors.primary,
        color: '#fff',
        padding: 10,
      },
      sformlabel: {
        fontSize: 14,
        color: colors.primary,
        width: '40%',
      },
      sformvalue: {
        fontSize: 14,
        color: colors.secondary,
        width: '60%',
        marginLeft: 20,
        paddingVertical: 0,
      },
      sformhead2: {
        fontSize: 16,
        color: "#000",
        paddingVertical: 10,
        // marginLeft: 20,
      },
      sformhr: {
        height: 1,
        backgroundColor: colors.secondary,
        marginVertical: 10,
        width: '90%',
        alignSelf: 'center',
      },
      formedit: {
        backgroundColor: colors.quadinary,
        padding: 10,
        width: 50,
        height: 50,
        borderRadius: 50,
        color: '#fff',
        textAlign: 'center',
        position: 'absolute',
        right: 10,
        bottom: 10,
        zIndex: 1,
      },
      formbtn: {
        backgroundColor: colors.primary,
        padding: 10,
        width: '40%',
        alignSelf: 'center',
        textAlign: 'center',
        color: '#fff',
        borderRadius: 20,
        margin: 20,
      },
      sformlabelh: {
        fontSize: 14,
        color: "black",
        width: '60%',
      },
      sformvalueh: {
        fontSize: 14,
        color: "black",
        width: '40%',
        marginLeft: 20,
      },
      sforminput: {
        fontSize: 14,
        borderWidth: 1,
        borderColor: '#ccc',
        width: '60%',
        marginHorizontal: 10,
        padding: 5,
        color: colors.secondary,
      }
}