module.exports = {
    colors: {
        primary: '#A16CE6',
        secondary: '#8F8E8E',
        tertiary: '#FF5722',
        quadinary: '#FEBD11',
    },
    fullbg1: {
        backgroundColor: '#A16CE6',
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        height: '100%',
    },
    fonts: {
        font1: 'Roboto',
        font2: 'sans-serif',
        font3: 'arial',
    },
    head1: {
        fontSize: 40,
        color: '#A16CE6',
        fontFamily: 'Roboto',
        fontWeight: 'bold',
        // backgroundColor: 'green',
        alignSelf: 'center',
    },
    head2: {
        fontSize: 40,
        color: 'white',
        fontFamily: 'Roboto',
        fontWeight: 'bold',
        // backgroundColor: 'green',
        alignSelf: 'center',
    },
    text1: {
        fontSize: 16,
        color: '#8F8E8E',
        fontFamily: 'Roboto',
        // fontWeight: 'bold',
        alignSelf: 'center',
    },
    padding10: {
        padding: 10,

    },
    formcont1: {
        width: '80%',
        alignSelf: 'center',
        // backgroundColor: 'red',
        margin: 5,
    },
    label: {
        fontSize: 14,
        color: '#8F8E8E',
        padding: 5,
    },
    fontcont1in: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#C8D0E1',
        borderRadius: 20,
        padding: 10,
        paddingHorizontal: 20,
    },
    input: {
        fontSize: 16,
        marginLeft: 10,
        color: '#A16CE6',
        width: '100%',
        padding: 0,
    },
    link1: {
        fontSize: 14,
        color: '#A16CE6',
        alignSelf: 'flex-end',
    },
    button: {
        fontSize: 16,
        color: '#fff',
        backgroundColor: '#A16CE6',
        width: 200,
        alignSelf: 'center',
        textAlign: 'center',
        padding: 10,
        borderRadius: 10,
        margin: 10,
        fontWeight: 'bold',
    },
    link21: {
        fontSize: 13,
        color: '#8F8E8E',
        alignSelf: 'center',
        margin: 10,
    },
    link22: {
        color: '#A16CE6',
    },
    label1: {
        fontSize: 16,
        color: 'white',
        padding: 5,
        alignSelf: 'center',
        textAlign: 'center',
        margin: 10,
    },
    input1: {
        fontSize: 20,
        marginLeft: 10,
        color: '#A16CE6',
        width: '100%',
        fontWeight: 'bold',
        padding: 0,
    },
    button1: {
        fontSize: 16,
        color: '#A16CE6',
        backgroundColor: '#fff',
        width: 250,
        alignSelf: 'center',
        textAlign: 'center',
        padding: 10,
        borderRadius: 10,
        margin: 20,
        fontWeight: 'bold',
    },
    link31: {
        fontSize: 15,
        color: '#C8D0E1',
        alignSelf: 'center',
        margin: 5,
    },
    link32: {
        color: 'white',
    },
    fontcont1in1: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'white',
        borderRadius: 20,
        padding: 10,
        paddingHorizontal: 20,
    },
}

